"""init

Revision ID: 28286d28b0e5
Revises: 
Create Date: 2026-09-16 16:31:41.823379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '28286d28b0e5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_app_settings'))
    )
    op.create_table('dialog_stages',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_dialog_stages'))
    )
    op.create_table('emotional_states',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_emotional_states'))
    )
    op.create_table('interference_types',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_interference_types'))
    )
    op.create_table('services',
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_services'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_users_created_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('entity_type', sa.String(length=32), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_log_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_index('ix_audit_log_cat_ts', 'audit_log', ['category', 'timestamp'], unique=False)
    op.create_index(op.f('ix_audit_log_category'), 'audit_log', ['category'], unique=False)
    op.create_index(op.f('ix_audit_log_timestamp'), 'audit_log', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_log_user_id'), 'audit_log', ['user_id'], unique=False)
    op.create_table('incident_types',
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('service_code', sa.String(length=8), nullable=False),
    sa.Column('parent_code', sa.String(length=16), nullable=True),
    sa.Column('priority', sa.String(length=16), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['parent_code'], ['incident_types.code'], name=op.f('fk_incident_types_parent_code_incident_types')),
    sa.ForeignKeyConstraint(['service_code'], ['services.code'], name=op.f('fk_incident_types_service_code_services')),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_incident_types'))
    )
    op.create_index(op.f('ix_incident_types_is_active'), 'incident_types', ['is_active'], unique=False)
    op.create_index(op.f('ix_incident_types_name'), 'incident_types', ['name'], unique=False)
    op.create_index(op.f('ix_incident_types_parent_code'), 'incident_types', ['parent_code'], unique=False)
    op.create_index(op.f('ix_incident_types_service_code'), 'incident_types', ['service_code'], unique=False)
    op.create_table('incident_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('incident_type_code', sa.String(length=16), nullable=True),
    sa.Column('subtype', sa.String(length=128), nullable=True),
    sa.Column('priority', sa.String(length=16), nullable=True),
    sa.Column('fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('validation', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['incident_type_code'], ['incident_types.code'], name=op.f('fk_incident_cards_incident_type_code_incident_types')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_incident_cards'))
    )
    op.create_index(op.f('ix_incident_cards_incident_type_code'), 'incident_cards', ['incident_type_code'], unique=False)
    op.create_index(op.f('ix_incident_cards_source'), 'incident_cards', ['source'], unique=False)
    op.create_table('scenarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('incident_type_code', sa.String(length=16), nullable=True),
    sa.Column('caller_profile', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_scenarios_author_id_users')),
    sa.ForeignKeyConstraint(['incident_type_code'], ['incident_types.code'], name=op.f('fk_scenarios_incident_type_code_incident_types')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scenarios'))
    )
    op.create_index(op.f('ix_scenarios_author_id'), 'scenarios', ['author_id'], unique=False)
    op.create_index(op.f('ix_scenarios_incident_type_code'), 'scenarios', ['incident_type_code'], unique=False)
    op.create_index(op.f('ix_scenarios_is_active'), 'scenarios', ['is_active'], unique=False)
    op.create_index(op.f('ix_scenarios_title'), 'scenarios', ['title'], unique=False)
    op.create_table('action_traces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.Column('is_reference', sa.Boolean(), nullable=False),
    sa.Column('total_time_sec', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], name=op.f('fk_action_traces_operator_id_users')),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], name=op.f('fk_action_traces_scenario_id_scenarios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_action_traces'))
    )
    op.create_index(op.f('ix_action_traces_is_reference'), 'action_traces', ['is_reference'], unique=False)
    op.create_index(op.f('ix_action_traces_scenario_id'), 'action_traces', ['scenario_id'], unique=False)
    op.create_table('scenario_outcomes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('classification_correct', sa.Boolean(), nullable=True),
    sa.Column('fields_required', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('fields_optional', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('time_to_classify_sec', sa.Integer(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], name=op.f('fk_scenario_outcomes_scenario_id_scenarios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scenario_outcomes')),
    sa.UniqueConstraint('scenario_id', name=op.f('uq_scenario_outcomes_scenario_id'))
    )
    op.create_table('scenario_turns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('turn_index', sa.Integer(), nullable=False),
    sa.Column('speaker', sa.String(length=16), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('timestamp_sec', sa.Float(), nullable=True),
    sa.Column('stage', sa.String(length=32), nullable=True),
    sa.Column('expected_action', sa.String(length=64), nullable=True),
    sa.Column('is_key_question', sa.Boolean(), nullable=False),
    sa.Column('emotional_marker', sa.String(length=32), nullable=True),
    sa.Column('contains_address', sa.Boolean(), nullable=False),
    sa.Column('contains_name', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['emotional_marker'], ['emotional_states.code'], name=op.f('fk_scenario_turns_emotional_marker_emotional_states')),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], name=op.f('fk_scenario_turns_scenario_id_scenarios'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stage'], ['dialog_stages.code'], name=op.f('fk_scenario_turns_stage_dialog_stages')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scenario_turns'))
    )
    op.create_index(op.f('ix_scenario_turns_scenario_id'), 'scenario_turns', ['scenario_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trainee_id', sa.Integer(), nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('report', sa.Text(), nullable=False),
    sa.Column('turns_log', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('actions_log', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('evaluation', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], name=op.f('fk_sessions_scenario_id_scenarios')),
    sa.ForeignKeyConstraint(['trainee_id'], ['users.id'], name=op.f('fk_sessions_trainee_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions'))
    )
    op.create_index(op.f('ix_sessions_scenario_id'), 'sessions', ['scenario_id'], unique=False)
    op.create_index(op.f('ix_sessions_trainee_id'), 'sessions', ['trainee_id'], unique=False)
    op.create_table('action_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trace_id', sa.Integer(), nullable=False),
    sa.Column('step', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=64), nullable=False),
    sa.Column('timestamp_sec', sa.Float(), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['trace_id'], ['action_traces.id'], name=op.f('fk_action_steps_trace_id_action_traces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_action_steps'))
    )
    op.create_index(op.f('ix_action_steps_action_type'), 'action_steps', ['action_type'], unique=False)
    op.create_index(op.f('ix_action_steps_trace_id'), 'action_steps', ['trace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_action_steps_trace_id'), table_name='action_steps')
    op.drop_index(op.f('ix_action_steps_action_type'), table_name='action_steps')
    op.drop_table('action_steps')
    op.drop_index(op.f('ix_sessions_trainee_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_scenario_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_scenario_turns_scenario_id'), table_name='scenario_turns')
    op.drop_table('scenario_turns')
    op.drop_table('scenario_outcomes')
    op.drop_index(op.f('ix_action_traces_scenario_id'), table_name='action_traces')
    op.drop_index(op.f('ix_action_traces_is_reference'), table_name='action_traces')
    op.drop_table('action_traces')
    op.drop_index(op.f('ix_scenarios_title'), table_name='scenarios')
    op.drop_index(op.f('ix_scenarios_is_active'), table_name='scenarios')
    op.drop_index(op.f('ix_scenarios_incident_type_code'), table_name='scenarios')
    op.drop_index(op.f('ix_scenarios_author_id'), table_name='scenarios')
    op.drop_table('scenarios')
    op.drop_index(op.f('ix_incident_cards_source'), table_name='incident_cards')
    op.drop_index(op.f('ix_incident_cards_incident_type_code'), table_name='incident_cards')
    op.drop_table('incident_cards')
    op.drop_index(op.f('ix_incident_types_service_code'), table_name='incident_types')
    op.drop_index(op.f('ix_incident_types_parent_code'), table_name='incident_types')
    op.drop_index(op.f('ix_incident_types_name'), table_name='incident_types')
    op.drop_index(op.f('ix_incident_types_is_active'), table_name='incident_types')
    op.drop_table('incident_types')
    op.drop_index(op.f('ix_audit_log_user_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_timestamp'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_category'), table_name='audit_log')
    op.drop_index('ix_audit_log_cat_ts', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_table('users')
    op.drop_table('services')
    op.drop_table('interference_types')
    op.drop_table('emotional_states')
    op.drop_table('dialog_stages')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
