"""add backup_records

Revision ID: 692982b70269
Revises: 28a50f90119a
Create Date: 2026-09-17 19:56:29.369894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '692982b70269'
down_revision: Union[str, Sequence[str], None] = '28a50f90119a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        'backup_records',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('filename', sa.String(length=255), nullable=False),
        sa.Column('size_bytes', sa.BigInteger(), nullable=False),
        sa.Column('kind', sa.String(length=16), nullable=False),
        sa.Column('status', sa.String(length=16), nullable=False),
        sa.Column('error', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('created_by_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_backup_records_created_at'), 'backup_records', ['created_at'], unique=False)
    op.create_index(op.f('ix_backup_records_filename'), 'backup_records', ['filename'], unique=True)
    op.create_index(op.f('ix_backup_records_status'), 'backup_records', ['status'], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_backup_records_status'), table_name='backup_records')
    op.drop_index(op.f('ix_backup_records_filename'), table_name='backup_records')
    op.drop_index(op.f('ix_backup_records_created_at'), table_name='backup_records')
    op.drop_table('backup_records')
    # ### end Alembic commands ###
